from __future__ import annotations

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

OUTPUT_DIRS = (
    "outputs",
    "outputs/cross_section",
    "outputs/panel",
    "outputs/logs",
    "outputs/intermediate",
)

GENERATED_OUTPUT_FILES = (
    "docs/_data_dictionary_cross_section.md",
    "docs/_data_dictionary_panel.md",
    "docs/cross_section_reproduction.md",
    "docs/data_dictionary.md",
    "docs/data_inventory.csv",
    "docs/cross_section_reproduction_results.md",
    "docs/panel_reproduction.md",
    "docs/panel_reproduction_results.md",
    "docs/phase0_audit.md",
    "docs/reproduction_results.md",
    "outputs/cross_section/cross_section_data_inventory.csv",
    "outputs/cross_section/cross_section_preparation_summary.csv",
    "outputs/cross_section/descriptive_statistics.csv",
    "outputs/cross_section/descriptive_statistics.html",
    "outputs/cross_section/diagnostics.csv",
    "outputs/cross_section/diagnostics.html",
    "outputs/cross_section/figures/correlation_plot.png",
    "outputs/cross_section/figures/re4_o_cooks_distance.png",
    "outputs/cross_section/figures/re4_o_residual_qq.png",
    "outputs/cross_section/figures/re4_o_residuals_vs_fitted.png",
    "outputs/cross_section/ols_compliance_variants.csv",
    "outputs/cross_section/ols_compliance_variants.html",
    "outputs/cross_section/ols_full_sample.csv",
    "outputs/cross_section/ols_full_sample.html",
    "outputs/cross_section/ols_institutional_variants.csv",
    "outputs/cross_section/ols_institutional_variants.html",
    "outputs/cross_section/ols_main.csv",
    "outputs/cross_section/ols_main.html",
    "outputs/cross_section/ols_models.csv",
    "outputs/cross_section/ols_models.html",
    "outputs/cross_section/ols_outlier_filtered.csv",
    "outputs/cross_section/ols_outlier_filtered.html",
    "outputs/cross_section/re4_o_influence_diagnostics.csv",
    "outputs/cross_section/re4_o_influence_diagnostics.html",
    "outputs/cross_section/spearman_correlation_matrix.csv",
    "outputs/cross_section/spearman_correlation_matrix.html",
    "outputs/cross_section/spearman_growth_vs_cc_prop.csv",
    "outputs/cross_section/spearman_growth_vs_cc_prop.html",
    "outputs/cross_section/spearman_growth_vs_cc_total.csv",
    "outputs/cross_section/spearman_growth_vs_cc_total.html",
    "outputs/cross_section/variance_inflation_factors.csv",
    "outputs/cross_section/variance_inflation_factors.html",
    "outputs/intermediate/cross_section_model_data4_o_prepared.csv",
    "outputs/intermediate/cross_section_model_data4_prepared.csv",
    "outputs/intermediate/panel/alt.csv",
    "outputs/intermediate/panel/main.csv",
    "outputs/intermediate/panel/small.csv",
    "outputs/logs/run_all_summary.txt",
    "outputs/panel/descriptive_statistics.csv",
    "outputs/panel/descriptive_statistics.html",
    "outputs/panel/diagnostic_tests.csv",
    "outputs/panel/diagnostic_tests.html",
    "outputs/panel/figures/correlation_plot.png",
    "outputs/panel/fixed_effects_compliance_categories.csv",
    "outputs/panel/fixed_effects_compliance_categories.html",
    "outputs/panel/fixed_effects_main.csv",
    "outputs/panel/fixed_effects_main.html",
    "outputs/panel/models_main_reduced.csv",
    "outputs/panel/models_main_reduced.html",
    "outputs/panel/models_small_full.csv",
    "outputs/panel/models_small_full.html",
    "outputs/panel/models_small_reduced.csv",
    "outputs/panel/models_small_reduced.html",
    "outputs/panel/panel_models.csv",
    "outputs/panel/panel_models.html",
    "outputs/panel/spearman_correlation_matrix.csv",
    "outputs/panel/spearman_correlation_matrix.html",
    "outputs/panel/specification_tests.csv",
    "outputs/panel/specification_tests.html",
)

CORE_INPUT_FILES = (
    "2400-LIC-FII.pdf",
    "OUTLINE.md",
    "TODO.md",
    "README.md",
    "docs/ai_disclosure.md",
    "docs/contributions.md",
    "docs/limitations.md",
    "docs/methodology.md",
    "docs/reproduction_contract.md",
    "docs/cross_section_reproduction_results.md",
    "docs/data_dictionary.md",
    "docs/panel_reproduction_results.md",
    "docs/reproduction_results.md",
    "docs/source_annotations.md",
    "outputs/README.md",
    "scripts/audit_phase0.py",
    "scripts/inventory_data.py",
    "scripts/run_cross_section_data.py",
    "helpers/rds_to_csv.py",
    "cross-section/inorder.R",
    "panel/inorder_panel.R",
)

CROSS_SECTION_DATA_FILES = (
    "cross-section/data/CCCD_avg2010_19.rds",
    "cross-section/data/CCCD_detailed_avg2010_19.rds",
    "cross-section/data/CCCD_growth_final.rds",
    "cross-section/data/Democracy_avg2010_19.rds",
    "cross-section/data/GDPpc_current_initial_Data.rds",
    "cross-section/data/GDPpc_initial_in_2015usd_Data.rds",
    "cross-section/data/cc_growth_yty.rds",
    "cross-section/data/edu_initial_Data.rds",
    "cross-section/data/fertility_Data.rds",
    "cross-section/data/gdp_growth_Data.rds",
    "cross-section/data/geo_cepii.dta",
    "cross-section/data/gov_exp_Data.rds",
    "cross-section/data/gov_exp_edu_Data.rds",
    "cross-section/data/gov_milit_exp_Data.rds",
    "cross-section/data/inflation_cpi_Data.rds",
    "cross-section/data/inflation_gdpdeflator_Data.rds",
    "cross-section/data/investment_Data.rds",
    "cross-section/data/life_exp_initial_Data.rds",
    "cross-section/data/model_data.rds",
    "cross-section/data/model_data2.rds",
    "cross-section/data/model_data3.rds",
    "cross-section/data/model_data4.1.rds",
    "cross-section/data/model_data4.rds",
    "cross-section/data/model_data4_o.rds",
    "cross-section/data/oth_char.rds",
    "cross-section/data/tot2.rds",
    "cross-section/data/tot_Data.rds",
    "cross-section/data/trade_Data.rds",
)

PANEL_DATA_FILES = (
    "panel/data_panel/model_data.rds",
    "panel/data_panel/model_data2.rds",
    "panel/data_panel/small_plm.rds",
)

REFERENCE_OUTPUT_FILES = (
    "cross-section/tables_and_other/descriptive stat.html",
    "cross-section/tables_and_other/Corrplot.png",
    "cross-section/tables_and_other/Spearman's rho Correlation Test Results growth vs total.html",
    "cross-section/tables_and_other/Spearman's rho Correlation Test Results growth vs prop.html",
    "cross-section/tables_and_other/reg_table1.html",
    "cross-section/tables_and_other/reg_table2&3.html",
    "cross-section/tables_and_other/reg_table_lv&prop.html",
    "cross-section/tables_and_other/reg_table_inst.html",
    "cross-section/tables_and_other/diagnostics.html",
    "panel/panel_tables/descriptive.html",
    "panel/panel_tables/Corrplot.png",
    "panel/panel_tables/Specification tests.html",
    "panel/panel_tables/Diagnostic tests.html",
    "panel/panel_tables/model_output.html",
    "panel/panel_tables/model_output2.html",
)

REQUIRED_PATHS = (
    *CORE_INPUT_FILES,
    *CROSS_SECTION_DATA_FILES,
    *PANEL_DATA_FILES,
    *REFERENCE_OUTPUT_FILES,
)


def resolve_repo_path(relative_path: str) -> Path:
    return PROJECT_ROOT / relative_path
