services:
  reproduction:
    build:
      context: .
      dockerfile: Dockerfile
    image: janwolyniak/reproducible-research-lic-fii
    command: python scripts/generate_report.py
    environment:
      MPLBACKEND: Agg
    volumes:
      - .:/app
